ReviewTrapHistoryEntity
N1NTENDO1999/DeratControl pull request #18
Opened 2019-09-08 16:30 UTC by MishkaSorochinskiy

2019-09-08 16:59 UTC, MishkaSorochinskiy commented
То Ігора

2019-09-11 09:15 UTC, SviatoslavMykhailiv requested changes

2019-09-11 09:15 UTC, SviatoslavMykhailiv commented on DeratControl.Domain/Entities/TrapReview.cs
> +    class TrapReview : EntityBase<int>
public

2019-09-11 09:15 UTC, SviatoslavMykhailiv commented on DeratControl.Domain/Entities/TrapReview.cs
> +        public Review Review { get; set; }
add ReviewId - a foreign key for a navigation property

2019-09-11 09:15 UTC, SviatoslavMykhailiv commented on DeratControl.Domain/Entities/TrapReview.cs
> +        public Review Review { get; set; }
private set

2019-09-11 09:15 UTC, SviatoslavMykhailiv commented on DeratControl.Domain/Entities/TrapReview.cs
> +        public Point Point { get; set; }
PointId, private set

2019-09-11 09:15 UTC, SviatoslavMykhailiv commented on DeratControl.Domain/Entities/TrapReview.cs
> +        public ICollection<TrapReviewImage> ListOfImages { get; set; }
private set

2019-09-11 09:15 UTC, SviatoslavMykhailiv commented on DeratControl.Domain/Entities/TrapReview.cs
> +        public TrapRewiewState TrapRewiewState { get; protected set; }
private set

2019-09-11 09:15 UTC, SviatoslavMykhailiv commented on DeratControl.Domain/Entities/TrapReview.cs
> +            this.ListOfImages = new List<TrapReviewImage>();
use field initializer instead

2019-09-11 16:54 UTC, HarryCopter1 commented
В комміт "fixed to private setters, field initializer, public class" випадково попали зміни, які робились для іншої таски, останні два комміта відміняли ці зміни

2019-09-12 08:15 UTC, merged