Unit of work
N1NTENDO1999/DeratControl pull request #30
Opened 2019-09-14 16:15 UTC by N1NTENDO1999

2019-09-14 16:29 UTC, VoitykRoman reviewed
l

2019-09-14 21:06 UTC, SviatoslavMykhailiv requested changes

2019-09-14 21:06 UTC, SviatoslavMykhailiv commented on DeratControl.Domain/Root/IUnitOfWork.cs
> +        void Commit();
make it asynchronous, Task Commit();

2019-09-14 21:06 UTC, SviatoslavMykhailiv commented on DeratControl.Ifrastructure/UnitOfWork.cs
> +        public void Commit()
Task Commit() { return DatabaseContext.SaveChangesAsync();}

2019-09-14 21:06 UTC, SviatoslavMykhailiv commented on DeratControl.Ifrastructure/DeratContext.cs
> +        public DbSet<Facility> Facilities { get; set; }
make all setters for Dbsets private

2019-09-15 08:12 UTC, N1NTENDO1999 commented on DeratControl.Ifrastructure/DeratContext.cs
> +        public DbSet<Facility> Facilities { get; set; }
Done

2019-09-15 08:13 UTC, SviatoslavMykhailiv approved these changes

2019-09-15 08:13 UTC, SviatoslavMykhailiv commented on DeratControl.Ifrastructure/UnitOfWork.cs
> +                    facilityRepository = new FacilityRepository(DatabaseContext);
Consider using Lazy<T> class

2019-09-15 08:13 UTC, SviatoslavMykhailiv commented on DeratControl.Ifrastructure/UnitOfWork.cs
> +                    facilityRepository = new FacilityRepository(DatabaseContext);
https://docs.microsoft.com/en-us/dotnet/api/system.lazy-1?view=netframework-4.8

2019-09-16 08:36 UTC, merged